### ISSUE TITLE
Issue with Fan of Knives and Hubris

### ISSUE THREAD

**Issue by STSsadoni** [RattusInVitaReali/RatMod#2]
I get a crash every time I play Fan of Knives with Hubris active.   Here's the exception report.

Exception: java.lang.NullPointerException
05:24:52.599 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:24) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:37) ~[desktop-1.0.jar:?]
	at ratmod.cards.FanOfKnives.use(FanOfKnives.java:51) ~[RatMod.jar:?]
	at com.evacipated.cardcrawl.mod.hubris.patches.ZylophonePatch$MultiUse.use(ZylophonePatch.java:51) ~[Hubris.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1594) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:159) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:283) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2531) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:883) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:435) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by kiooeht** [comment]
Hey, I got this sent to me too because ZylophonePatch appears in it.

I believe the issue is on your end. If you use `multiDamage` in a card, you also need to set `isMultiDamage = true;` in the card's constructor, which you're not doing.

Example from Blizzard:
```Java
  public Blizzard()
  {
    super("Blizzard", NAME, "blue/attack/blizzard", 1, DESCRIPTION, AbstractCard.CardType.ATTACK, AbstractCard.CardColor.BLUE, AbstractCard.CardRarity.UNCOMMON, AbstractCard.CardTarget.ALL_ENEMY);
    
    this.baseDamage = 0;
    this.baseMagicNumber = 2;
    this.magicNumber = this.baseMagicNumber;
    this.isMultiDamage = true; // This
  }
```

**Comment by RattusInVitaReali** [comment]
Okay, will look into it. Thanks for isolating the issue, always helps a lot.
